networks:
  default: kovan
dotenv: .env
wallets: 
  from_key: ${PRIVATE_KEY}
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.0.0"
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.0"
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.0.0
  - smartcontractkit/chainlink-brownie-contracts@0.4.0